<a href="https://colab.research.google.com/github/moshiurrahman1998/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

tensors


In [3]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.6088, -0.0081,  1.1279,  1.7794],
        [-1.1452, -0.9494,  0.0105,  0.3916],
        [ 0.4091,  0.2790,  0.7537, -0.4648]])

In [4]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# prompt: create tensor out of numpy array

numpy_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = torch.from_numpy(numpy_array)
tensor_from_numpy


In [8]:

# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(2,-1)

my_torch2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])